### ISSUE TITLE
(POSTPONED)Adding getBoundClientRect to UI to change appearence of element by scroll event

### ISSUE THREAD

**Issue by OwnTooManyMonster** [OwnTooManyMonster/capstone#1]
## Value statement - a requirement, not a solution
As a user
I need / want to see the Element that is 100% visible in viewport to be highlighted
so that the navigation is easier since the focus is visually assited
## Acceptance criteria
- [ ] (Review)
- [ ] (when element is highlighted when in focus of screen)

## Tasks
- [x] (adding components for getbound and implement iteration in index.js)
- [ ] (adding the math calculation for the vievable field in if statement)
- [ ] (adding the css toggle if statement is fullfiled)

## Size
(medium)
