### ISSUE TITLE
Implementing logic for data backup if offline or fetch fail

### ISSUE THREAD

**Issue by OwnTooManyMonster** [OwnTooManyMonster/capstone#17]
## Value statement - a requirement, not a solution
As a (user)
I need / want (redundant local data)
so that (i can access the app visualisation all time)

## Acceptance criteria
- [ ] (Running App in offline mode)

## Tasks
- [ ] (Implementing the backup data )
- [ ] (Implementing the redundancy logis

## Size
(medium,)
