### ISSUE TITLE
Implementation of Mapbox in Ocean Link 10h

### ISSUE THREAD

**Issue by OwnTooManyMonster** [OwnTooManyMonster/capstone#4]
manuelremer to Everyone (1:07 PM)
## Value statement - a requirement, not a solution
As a (customer)
I need / want (a discoverable Map with predefined coordinates)
so that (i can visually see the source of data)

## Acceptance criteria
- [x] (functional visual map in App)
- [x] (functional locations in Map)

## Tasks
- [x] (Implementation in HTML/CSS)
- [x] (Implementation of necessary Javascript)

## Size
( large)
