### ISSUE TITLE
Changing Video source from local to cloud

### ISSUE THREAD

**Issue by OwnTooManyMonster** [OwnTooManyMonster/capstone#7]
## Value statement - a requirement, not a solution

Changing source

## Acceptance criteria
- [ ] (Access from cloud)
 - [ ] (Acceptable loading time)

## Tasks
- [ ] (upload and chnge of src)
- [ ] (Solving issue with tracing rejection)

## Size
( medium,)
